In [3]:
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn import svm

digits=datasets.load_digits()
clf=svm.SVC(gamma=0.001,C=100)
x,y=digits.data[:-10],digits.target[:-10]
clf.fit(x,y)
print 'Prediction:',clf.predict(digits.data[-2])
plt.imshow(digits.images[-2],cmap=plt.cm.gray_r,interpolation="nearest")
plt.show()

Prediction: [9]


In [20]:
svm.SVC?

In [8]:
print digits.data[0]
print '11111111111111111111111111'
print digits.images[0]

[  0.   0.   5.  13.   9.   1.   0.   0.   0.   0.  13.  15.  10.  15.   5.
   0.   0.   3.  15.   2.   0.  11.   8.   0.   0.   4.  12.   0.   0.   8.
   8.   0.   0.   5.   8.   0.   0.   9.   8.   0.   0.   4.  11.   0.   1.
  12.   7.   0.   0.   2.  14.   5.  10.  12.   0.   0.   0.   0.   6.  13.
  10.   0.   0.   0.]
11111111111111111111111111
[[  0.   0.   5.  13.   9.   1.   0.   0.]
 [  0.   0.  13.  15.  10.  15.   5.   0.]
 [  0.   3.  15.   2.   0.  11.   8.   0.]
 [  0.   4.  12.   0.   0.   8.   8.   0.]
 [  0.   5.   8.   0.   0.   9.   8.   0.]
 [  0.   4.  11.   0.   1.  12.   7.   0.]
 [  0.   2.  14.   5.  10.  12.   0.   0.]
 [  0.   0.   6.  13.  10.   0.   0.   0.]]


In [11]:
from __future__ import print_function
#from IPython.html.widgets import interact, interactive, fixed
#from IPython.html import widgets
from ipywidgets import interact, interactive, fixed,interact_manual

@interact_manual(x="",y=[('one', 10), ('two', 20)])
def f(x,y):
    print(x)
    print(y)
#interact(f, x=10);

interactive(children=(Text(value='', description='x'), Dropdown(description='y', options=(('one', 10), ('two',…

In [14]:
def h(p, q):
    print(p, q)
interact(h, p='dfdf', q='ggggg');

dfdf999888 ggggg


In [17]:
from IPython.html.widgets import *
Text(value='Hello World!', disabled=False)

In [13]:
from sklearn import datasets
iris = datasets.load_iris()
digits = datasets.load_digits()

from sklearn import neighbors
knn = neighbors.KNeighborsClassifier()
knn.fit(iris.data, iris.target)
knn.predict([[4.7, 5.7, 10.9, 6.9]])


array([2])

In [42]:
s='dffdff'
s.split??

In [44]:
%quickref

In [18]:
def func(x):
    return x*2+3

data=[]
target=[]
data.append(1)
target.append(func(1))
data.append(2)
target.append(func(2))
data.append(3)
target.append(func(3))
data.append(4)
target.append(func(4))

print (data)
print (target)

[1, 2, 3, 4]
[5, 7, 9, 11]


In [19]:
from sklearn import linear_model
clf = linear_model.LinearRegression()
clf.fit(data, target)
clf.predict(6)

ValueError: Expected 2D array, got 1D array instead:
array=[1 2 3 4].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.